services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=PlanetShop'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5000:5432'